version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: cibuilds/hugo:latest

    working_directory: ~/hugo

    environment:
      - HUGO_BUILD_DIR: ~/hugo/public
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages

    steps:
      - checkout

      - add_ssh_keys

      - run:
          name: Install php and php extensions
          command: |
            apk update && apk add php7
            apk add php7-curl php7-iconv php7-json php7-mbstring php7-openssl php7-xml php7-phar php7-tokenizer php7-dom
      
      - run:
          name: Install composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      
      - run:
          name: Install terminus
          command: |
            curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install

      - run:
          name: Build
          command: ./.circleci/scripts/build.sh
            

      - run:
          name: Run hugo
          command: HUGO_ENV=production hugo -v

      # - deploy:
      #     name: Deploy
      #     command: ./.circleci/scripts/deploy.sh

