version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: cibuilds/hugo:latest

    working_directory: ~/hugo

    environment:
      - HUGO_BUILD_DIR: ~/hugo/public
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages

    steps:
      - checkout

      - add_ssh_keys
          fingerprints:
            - "c9:7d:25:cc:9d:6f:ef:3e:a7:ad:2b:5a:04:35:35:b3"

      - run:
          name: Run hugo
          command: HUGO_ENV=production hugo -v

      - deploy:
          name: Deploy
          command: ./.circleci/scripts/deploy.sh

