version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: cibuilds/hugo:latest

    working_directory: ~/hugo

    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages

    steps:
      - checkout

      - add_ssh_keys

      - run:
          name: Install php and php extensions
          command: |
            apk update && apk add php7
            apk add php7-curl php7-iconv php7-json php7-mbstring php7-openssl php7-xml php7-phar php7-tokenizer php7-dom
      
      - run:
          name: Install composer
          command: ./.circleci/scripts/install-composer.sh
      
      - run:
          name: Install terminus
          command: |
            curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install

      - run:
          name: Build and deploy
          command: ./.circleci/scripts/build-deploy.sh

